package co.edu.icesi.banco.modelo;
// Generated 22/05/2018 12:10:38 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TiposDocumentos generated by hbm2java
 */
@Entity
@Table(name = "tipos_documentos", schema = "public")
public class TiposDocumentos implements java.io.Serializable {

	private long tdocCodigo;
	private String tdocNombre;
	private String tdocHabilitado;
	private Set<Clientes> clienteses = new HashSet<Clientes>(0);

	public TiposDocumentos() {
	}

	public TiposDocumentos(long tdocCodigo, String tdocNombre, String tdocHabilitado) {
		this.tdocCodigo = tdocCodigo;
		this.tdocNombre = tdocNombre;
		this.tdocHabilitado = tdocHabilitado;
	}

	public TiposDocumentos(long tdocCodigo, String tdocNombre, String tdocHabilitado, Set<Clientes> clienteses) {
		this.tdocCodigo = tdocCodigo;
		this.tdocNombre = tdocNombre;
		this.tdocHabilitado = tdocHabilitado;
		this.clienteses = clienteses;
	}

	@Id

	@Column(name = "tdoc_codigo", unique = true, nullable = false, precision = 10, scale = 0)
	public long getTdocCodigo() {
		return this.tdocCodigo;
	}

	public void setTdocCodigo(long tdocCodigo) {
		this.tdocCodigo = tdocCodigo;
	}

	@Column(name = "tdoc_nombre", nullable = false, length = 50)
	public String getTdocNombre() {
		return this.tdocNombre;
	}

	public void setTdocNombre(String tdocNombre) {
		this.tdocNombre = tdocNombre;
	}

	@Column(name = "tdoc_habilitado", nullable = false, length = 2)
	public String getTdocHabilitado() {
		return this.tdocHabilitado;
	}

	public void setTdocHabilitado(String tdocHabilitado) {
		this.tdocHabilitado = tdocHabilitado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposDocumentos")
	public Set<Clientes> getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set<Clientes> clienteses) {
		this.clienteses = clienteses;
	}

}
